package models

type Pupil struct {
	Id                     string `xorm:"'id' <-"`
	AdmissionNo            int    `xorm:"'admission_no'"`
	User_id                string `xorm:"'user_id'"`
	Parent_id              string `xorm:"'parent_id'"`
	JoiningDate            string `xorm:"'joiningdate'"`
	JoiningAcademicTerm_id string `xorm:"'joiningacademicterm_id'"`
}

func (*Pupil) TableName() string {
	return "pupils"
}

// ---------------- SQL VERSION ----------------

// CREATE TABLE "pupils" (
// 	"id" uuid DEFAULT uuid_generate_v4() PRIMARY KEY,
// 	"admission_no" INT GENERATED BY DEFAULT AS IDENTITY UNIQUE NOT NULL,
// 	"user_id" uuid,
// 	"parent_id" uuid,
// 	"joiningdate" timestamp NOT NULL,
// 	"joiningacademicterm_id" uuid
//   );
